version: '3'
services:
  app:
    container_name: picrate-api
    image: sjsage522/picrate-api
    expose: 
      - 8082
    ports:
      - 8082:8082
    volumes:
      - /data/files/*:/data/files/*
      - /var/log/nohup.out:/var/log/nohup.out
  
  nginx:
    container_name: picrate-proxy
    image: sjsage522/picrate-proxy
    ports:
      - 80:80
    volumes:
      - /etc/nginx/*:/etc/nginx/*
      - /var/log/nginx*:/var/log/nginx*
      - /var/www/html/*://usr/share/nginx/html/*
    depends_on:
      - app
