version: '3'
services:
  app1:
    restart: always
    container_name: picrate-api-1
    image: sjsage522/picrate-api
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - /data/files:/data/files
      - /var/log/app-api:/var/log/app-api
    depends_on:
      - db

  app2:
    restart: always
    container_name: picrate-api-2
    image: sjsage522/picrate-api
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - /data/files:/data/files
      - /var/log/app-api:/var/log/app-api
    depends_on:
      - db

#  nginx:
#    container_name: picrate-proxy
#    image: sjsage522/picrate-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/log/nginx:/var/log/nginx
#      - /usr/share/nginx/html:/usr/share/nginx/html
#      - /etc/letsencrypt:/etc/letsencrypt
#    depends_on:
#      - app1
#      - app2

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    expose:
      - "3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  db-adminer:
    container_name: db-adminer
    image: adminer:latest
    ports:
      - "9000:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce

volumes:
  mysql_data:
  mysql_config: