version: '3'
services:
  app1:
    container_name: picrate-api-1
    image: sjsage522/picrate-api
    expose:
      - "8082"
    volumes:
      - /data/files/*:/data/files/*
      - /var/log/nohup.out:/var/log/nohup.out
  
  app2:
    container_name: picrate-api-2
    image: sjsage522/picrate-api
    expose:
      - "8082"
    volumes:
      - /data/files/*:/data/files/*
      - /var/log/nohup.out:/var/log/nohup.out

  nginx:
    container_name: picrate-proxy
    image: sjsage522/picrate-proxy
    ports:
      - 80:80
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app1
      - app2
