server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-http-form-post-size: 500000000
    max-swallow-size: 500000000
      
spring:
  profiles:
    default: prod
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: "/static/**"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        

logging:
  file:
    name: ${base-log-path}/app-api.log
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 100MB