server:
  error:
    whitelabel:
      enabled: false
      
spring:
  profiles:
    default: prod
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: "/static/**"

logging:
  file:
    name: ${base-log-path}/app-api.log
    max-history: 30
    max-size: 100MB
  # level: